<?php


namespace App\Http\Controllers;


use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Tests\TestCase;

class LogControllerTest extends TestCase
{
    use WithoutMiddleware, RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * This test is case getLogs success
     */
    public function testGetLogsSucess(): void
    {
        $this->artisan('db:seed --class=PaymentsSeeder');

        $response = $this->get(route('log.getLogs'), ['Accept' => 'application/json']);

        $response->assertStatus(200);
    }

    /**
     * This test is case getLogs Error
     */
    public function testGetLogsError(): void
    {
        $response = $this->get(route('log.getLogs'), ['Accept' => 'application/json']);

        $response->assertStatus(500);
    }
}
