<?php


namespace App\Http\Controllers;


use App\Models\CashFlow;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Tests\TestCase;

class PaymentControllerTest extends TestCase
{
    use WithoutMiddleware, DatabaseTransactions;

    /**
     * @var mixed
     */
    protected $body;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->body = $this->getDataCreate();
        $this->artisan('db:seed --class=PaymentsSeeder');
    }

    /**
     * @return mixed
     */
    private function getDataCreate()
    {
        $body = file_get_contents(__DIR__ . '/../../../RequestFiles/bodyPaymentCreate.json');
        return json_decode($body, true);
    }

    public function testCreatePayment(){
        $response = $this->post(route('payment.create'), $this->body, ['Accept' => 'application/json']);
        dd($response);
        $response->assertStatus(201);
    }
}
